import = [
	"~/.config/alacritty/themes/catppuccin_macchiato.toml"
]
[env]

TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

dimensions = { columns = 230, lines = 90 }

decorations = "Buttonless"

opacity = 0.75
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono" 

size = 12

