#!/bin/bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/music.sh"

#source "$ITEM_DIR/cron.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"

if system_profiler SPPowerDataType 2>/dev/null | grep -q "Battery Information"; then
    source "$ITEM_DIR/battery.sh"
fi

source "$ITEM_DIR/cpu.sh"
#source "$ITEM_DIR/caffeinate.sh"


if networksetup -getairportnetwork en0 2>/dev/null | grep -q "Current Wi-Fi Network"; then
    source "$ITEM_DIR/wifi.sh"
fi

#source "$ITEM_DIR/weather.sh"

sketchybar --update

