#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add item memory_spacer_right right \
           --set      memory_spacer_right \
                      background.drawing=off

sketchybar --add item memory right \
           --set memory \
                 background.drawing=off \
                 icon.drawing=on \
                 icon="󰘚" \
                 icon.font="JetBrainsMono Nerd Font:Bold:14.0" \
                 icon.color="$LABEL_COLOR" \
                 icon.padding_left=0 \
                 icon.padding_right=5 \
                 label.color="$LABEL_COLOR" \
                 label.padding_left=0 \
                 label.padding_right=0 \
                 update_freq=10 \
                 script="$PLUGIN_DIR/memory" \
           --subscribe memory \
                 mouse.entered \
                 mouse.exited

sketchybar --add item memory_spacer_left right \
           --set      memory_spacer_left \
                      background.drawing=off

sketchybar --add bracket memory_bracket memory_spacer_left memory memory_spacer_right \
           --set         memory_bracket \
                         background.border_color="$BRACKET_BACKGROUND_BORDER_COLOR" \
                         background.color="$BRACKET_BACKGROUND_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"