#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add item network_spacer_right right \
           --set      network_spacer_right \
                      background.drawing=off

sketchybar --add item network right \
           --set network \
                 background.drawing=off \
                 label.color="$LABEL_COLOR" \
                 label.padding_left=0 \
                 label.padding_right=0 \
                 update_freq=15 \
                 script="$PLUGIN_DIR/network"

sketchybar --add item network_spacer_left right \
           --set      network_spacer_left \
                      background.drawing=off

sketchybar --add bracket network_bracket network_spacer_left network network_spacer_right \
           --set         network_bracket \
                         background.border_color="$BRACKET_BACKGROUND_BORDER_COLOR" \
                         background.color="$BRACKET_BACKGROUND_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"